### ISSUE TITLE
Brightness widget, how to install?

### ISSUE THREAD

**Issue by Taddic** [streetturtle/awesome-wm-widgets#14]
Hi,
I submitted an issue some months ago and that seem to be working quite fine :)
Right now I was trying out the brightness widget and don't seem to be able to get it working and couldn't see any install instructions for it.
So far I added it as a require at the top of rc.lua and added:
	 s.mytasklist,
	 {
	    layout = wibox.layout.fixed.horizontal,
            - - 
	    brightness_widget,
            - -
	 },

The battery and volume widget works splendidly so far at least, very nice work! :)
Best regards,
Taddic

**Comment by streetturtle** [comment]
Hi! Thanks for raising an issue. I've updated the repo and added documentation. There was a problem with `xbacklight` command - for some laptops it doesn't work (don't know why, probably because of the video card, or video drivers). So you need first to check if it works for you, for example `xbacklight  -get` should return some value. If it doesn't work you have to install [`light`](https://github.com/haikarainen/light) and use it in the widget - see [docs](https://github.com/streetturtle/awesome-wm-widgets/tree/master/brightness-widget). Please let me know if it works.
Cheers!

**Comment by Taddic** [comment]
Hi,
Thanks for the instructions, it worked well! I had to install the 'light' command, but it worked like a charm.

I think you got the global keys mixed up:
awful.spawn("light -A 5") seem to increase the brightness.
awful.spawn("light -U 5") seem to decrease the brightness

I put in the following and got the brightness keys working properly on my laptop:
   awful.key({ }, "XF86MonBrightnessDown",
      function () awful.spawn("light -U 5") end,
      {description = "decrease brightness", group = "custom"}),
   awful.key({ }, "XF86MonBrightnessUp",
      function () awful.spawn("light -A 5") end,
      {description = "increase brightness", group = "custom"})

Thanks a lot for the help! And thanks for the github repo, your widgets are very useful!
/Taddic
