### ISSUE TITLE
battery warning at 100% and charging

### ISSUE THREAD

**Issue by hi-im-buggy** [streetturtle/awesome-wm-widgets#209]
I'm facing the same issue on my laptop when it's at 100% and charging, but not when it's not charging. `acpi` outputs 
```
Battery 0: Not charging, 99%
```
when this is the case and the widget shows 0% battery and a warning.
`acpi -a` outputs
```
Adapter 0: on-line
```
when I'm plugged in and
```
Adapter 0: off-line
```
when I'm not, so perhaps that can be helpful in finding a solution.

EDIT: To clarify, the widget shows 100% battery when I'm at 100% and *not* connected, and it shows 0% battery when I'm at 100% and connected.

_Originally posted by @hi-im-buggy in https://github.com/streetturtle/awesome-wm-widgets/issues/75#issuecomment-698264686_

**Comment by videla98** [comment]
I have the same issue, when the battery is at 100% and my laptop is plugged in the widget shows the battery at 0% and starts outputting warnings.

**Comment by videla98** [comment]
I solved the problem by editing batteryarc.lua and changing line 92 from:
`local cur_status, charge_str, _ = string.match(s, '.+: (%a+), (%d?%d?%d)%%,?(.*)')`
To:
`local cur_status, charge_str, _ = string.match(s, '.+: (%a+%s?%a*), (%d?%d?%d)%%,?(.*)')`
Line 104 from:
`if status == 'Charging' then`
To:
`if status == 'Charging' or status == 'Not charging' then`
And line 123 from:
`if enable_battery_warning and status ~= 'Charging' and os.difftime(os.time(), last_battery_check) > 300 then`
To:
`if enable_battery_warning and status ~= 'Charging' and status ~= 'Not charging' and os.difftime(os.time(), last_battery_check) > 300 then`

The problem was that acpi outputs "Not charging" as a status when the battery is full and connected and the widget wasn't considering it. I don't know if my fix would clash with some edge case in another system but it'll probably be enough for most people with the problem.

**Comment by andreaslongo** [comment]
I stumbled upon this issue yesterday and fixed it in a similar way to @videla98.

Problem:

When the battery is almost fully charged, and I plug in the AC, then the widget shows 0% for that battery.

If I disconnect the AC, the widget works as expected. It also works as expected if the battery is not almost fully charged, and I plug in the AC.

Cause:

That is related to the output of the `acpi` command and the widget's corresponding regex pattern.

```
$ acpi --version
acpi 1.7

# AC plugged in, battery almost full
$ acpi
Battery 0: Not charging, 99%

# AC disconnected
$ acpi
Battery 0: Discharging, 99%, 02:26:49 remaining

# AC plugged in, charging
Battery 0: Charging, 76%, 00:13:37 until charged
```

I prepared a PR that fixes the issue for me.
