### ISSUE TITLE
failed to open file: display-brightness-symbolic.svg [brightness widget]

### ISSUE THREAD

**Issue by senorsmile** [streetturtle/awesome-wm-widgets#232]
Where are these arc icons supposed to come from?  
I don't see anything on the main page or in the brightness-widget on additional steps.  

Full error: 
```
awesome: Failed to load '/usr/share/icons/Arc/status/symbolic/display-brightness-symbolic.svg': 
Failed to open file “/usr/share/icons/Arc/status/symbolic/display-brightness-symbolic.svg”: No such file or directory
```

**Comment by streetturtle** [comment]
When I created the widget I thought that widget should take icons from the system. The ones used in this widget are from this theme: https://github.com/horst3180/arc-icon-theme. But now I see that the better way would be to add icons to the widget sources, so that you don't need to preinstall anything. I'll update the widget source and will post here when it's done. For now you can just install the arc-icon theme.

**Comment by senorsmile** [comment]
Thanks!

**Comment by streetturtle** [comment]
I've added the icon to the widget folder. I've also refactor widget a bit. So feel free to pull the latest version and please let me know if it work ok
