### ISSUE TITLE
Logout menu and pop up not working

### ISSUE THREAD

**Issue by ThaumicTom** [streetturtle/awesome-wm-widgets#281]
Adding the logout menu in my rc.lua caused the following error:

[logout-menu-lua:118: attempt to call a nil value (method 'buttons')](https://github.com/streetturtle/awesome-wm-widgets/blob/a808ead3c74d57a7ccdb7f9e55cfa10a136d488c/logout-menu-widget/logout-menu.lua#L118)

rc.lua
```lua
local logout_menu_widget = require("awesome-wm-widgets.logout-menu-widget.logout-menu")
-- ...
screen.connect_signal("request::desktop_decoration", function(s)
    -- ...
    s.mywibox:setup {
        layout = wibox.layout.align.horizontal,
        -- ...
        s.mytasklist,
        { -- Right widgets
            layout = wibox.layout.fixed.horizontal,
            logout_menu_widget(),
        }
    }
end
```

A similar issue happens with the logout pop up, however it results in a generic error by awesome.

**Comment by streetturtle** [comment]
Do you use more than one screen?

**Comment by ThaumicTom** [comment]
I indeed am on a dual screen setup. So I probably can only display it once?

**Comment by zhisme** [comment]
Same here, I'm not using multiple screens only one, but yet couldn't start the widget, receiving same error.

**Comment by Aire-One** [comment]
This commit changed the widget `:buttons()` method to be a normal property. https://github.com/awesomeWM/awesome/commit/3d918258e2fefdb6696fa6c35150235144561c18

It means we should now use `widget.buttons = blah` instead of invoking a function.

This change is, however, not supposed to break the API, since the method `object.properties._legacy_accessors` should allow to keep backward compatibility with some meta-table magic.

We'll need to investigate this, more in depth and probably patch awesome. I'm escalating the issue to the awesome repository.

Alternatively, for people affected by this issue, it is possible to upgrade the code to use the new API as I shown earlier.

**Comment by Aire-One** [comment]
I did some investigation today. The `:buttons()` legacy method still exists, so Awesome backward compatibility is actually working.

The issue here isn't from Awesome, but from the widget implementation. The last line `return setmetatable(logout_menu_widget, logout_menu_widget.mt)` overwrite the base widget metatable. Hence, the magic that backports the legacy `:buttons` method no longer exists in `logout_menu_widget`.

A fix would be to somehow combine your `__call` implementation with the current metatable of `logout_menu_widget`. An even simpler fix, would be to simply return the `worker` function (it would however make the widget unavailable to modification from the module outside (if that's something you want to allow)).
