### ISSUE TITLE
I'd like to add a German locale in weather widget

### ISSUE THREAD

**Issue by paulhersch** [streetturtle/awesome-wm-widgets#295]
Hi,
I set up the weather widget and saw, that the German locale is missing. After looking at how they are implemented, i added it myself and now i want to put it in this repo. I just don't really know how git works, can somebody please assist me in committing the change?

**Comment by Ryuno-Ki** [comment]
Sure.

On https://github.com/streetturtle/awesome-wm-widgets/tree/master/weather-widget/locale in the GitHub UI (instead of, say, GitHub desktop app), you can see an „Add file” button in the upper right. Pick „Create new file” from the combobox.

The file name is „de.lua”.

Paste in the changes you made and scroll down to the bottom.
You can summarise the changes in couple of words (and write a longer explanation in the text block below) and then continue by clicking on the button.

This will lead you to the so-called Pull Request view, where your changes are compared to the changes in the current repo.
Add motivation (for example, by referencing this issue) and open a new Pull Request. From there, someone needs to review and approve the changes and they will make their way in to everybody.

I'm German speaking. Please feel free to reach out to me if you get stuck somewhere.
It's been a while since I touched Lua, but I think I can recall enough to get you over the finish line :-)

**Comment by paulhersch** [comment]
Well the file itself isn't really complicated, i already created it locally and it works, I wanted to try to do this from the command line but i think i would need to create an extra repo if i want to do it that way and that is way too much effort lol. Its just 12 lines
thanks for the help tho, very appreciated!

**Comment by paulhersch** [comment]
Created the PR, thanks for your help!

**Comment by Ryuno-Ki** [comment]
Yay, now we can enjoy the widget in German :partying_face:
