### ISSUE TITLE
[Calendar] `focus_date_bg` and `focus_date_fg` broken after updating to last commits

### ISSUE THREAD

**Issue by xfzv** [streetturtle/awesome-wm-widgets#426]
After updating to Oct 8, 2023 commits:
- 5a340913eef3a4b2fd6fd75329763ea916e26046
- cdcb543c86272feca1d51f6001478481b243912c
- 782f27168d857e09385dbb8585e059832afa056a
- 3fcb00cacd9630f3927a4d7e9fec9cf425d35f68

`focus_date_bg` and `focus_date_fg` colors are no longer working on my end, regardless of which theme is used.
Reverting to 7702f00efad8c1bcfa34b9e5cce4e99f3ac8bf1a solves the issue for me.

Screenshots (before/after):

- Nord
![image](https://github.com/streetturtle/awesome-wm-widgets/assets/78810647/1cf4dc8f-a192-4a36-8ec5-991da632f2e6)
![image](https://github.com/streetturtle/awesome-wm-widgets/assets/78810647/65529fa6-2672-4d98-8c99-7db287506ade)

- Outrun
![image](https://github.com/streetturtle/awesome-wm-widgets/assets/78810647/57172a15-f50c-46f0-aa3f-bd20ca5d4a8b)
![image](https://github.com/streetturtle/awesome-wm-widgets/assets/78810647/f73daade-eff8-411f-9d35-071b0bad83c2)

- Light
![image](https://github.com/streetturtle/awesome-wm-widgets/assets/78810647/b4fe7024-c5a4-4c3b-bdd6-0c38dff2267d)
![image](https://github.com/streetturtle/awesome-wm-widgets/assets/78810647/21912592-f95b-4fc2-9072-13c899940f36)

- Dark
![image](https://github.com/streetturtle/awesome-wm-widgets/assets/78810647/5d1ec3b2-fbd2-467d-8340-fb3f9887c24c)
![image](https://github.com/streetturtle/awesome-wm-widgets/assets/78810647/6947529c-70a4-423c-bcba-782b7142c3a9)

My config:

```lua
local lain = require("lain")
local markup = lain.util.markup
local wibox = require("wibox")

local calendar_widget = require("awesome-wm-widgets.calendar-widget.calendar")

local textclock = wibox.widget.textclock(
  markup("#CBA6F7", "🗓️")
    .. markup("#CDD6F4", " %a %b %d ")
    .. markup("#94E2D5", " 🕗")
    .. markup("#CDD6F4", " %H:%M ")
)

local cw = calendar_widget({
  theme = "naughty",
  placement = "top_right",
  previous_month_button = 4,
  next_month_button = 5,
})

textclock:connect_signal("button::press", function(_, _, _, button)
  if button == 1 then
    cw.toggle()
  end
end)

return textclock
```

Anyone else? Pinging @Luka5W considering he's the author of said commits.

**Comment by Luka5W** [comment]
the themes implementation in widgets seems a little bit complicated/ inconsistant imo but im not good at lua and new to awesome.

i'm using the theme `light` and its working fine. (see your 3rd screenshot ![https://user-images.githubusercontent.com/78810647/284698170-b4fe7024-c5a4-4c3b-bdd6-0c38dff2267d.png](https://user-images.githubusercontent.com/78810647/284698170-b4fe7024-c5a4-4c3b-bdd6-0c38dff2267d.png))
but i found this mysterious comment below:
`--theme = 'naughty', -- naughty theme is broken` in my rc.lua.

what is lain/ markup? have you tried making a backup of your user config, copying the default config (`/etc/xdg/awesome/rc.lua`) to yor config dir and modify it?
this is my config
```lua
-- Create a textclock widget
mytextclock = wibox.widget.textclock('%a, %Y-<b>%m</b>-<b>%d</b> // <b>%H</b>:<b>%M</b>:%S', 1)
local cw = calendar_widget({
    theme = 'light',
    --theme = 'naughty', -- naughty theme is broken
    placement = 'top_right',
    radius = 8,
    week_numbers = true,
})
```

i have not looked in the code yet but i believe the themes were designed for that broken naughty theme - or i have an old version or something. i guess i find some time in the next few days. streetturtle could revert the changes otherwise as a hotfix.

**Comment by Luka5W** [comment]
not quite sure what happened but i've got a (very) different version of calendar.lua. i believe i messed things up when i merged stuff in my fork -.-

**Comment by Luka5W** [comment]
naughty is kind of fixed with that solution. but i messed my codes completely now...

i believe it is because my theme (gtk) doesnt specify `fg` and`bg` but `fg_normal` and `bg_normal`.

the current behavior is:

cell(s) | bold | bg color | fg color
---|---|--|---
month/ year | yes | default | default
week days | yes | default | default
week nums | no | default | default
week days | no | default | default
weekend | no | focus | default
today | yes | fg color | bg color

focus (for internal themes) = any color which is a little bit lighter for dark themes or darker for light themes.
focus (for naughty theme) = focus color
default fg (for naughty theme) = `beautiful.notification_fg or beautiful.fg or beautiful.fg_normal`
default bg (for naughty theme) = `beautiful.notification_bg or beautiful.bg or beautiful.bg_normal`
