### ISSUE TITLE
Allow configuration without overwrites

### ISSUE THREAD

**Issue by Ryuno-Ki** [streetturtle/awesome-wm-widgets#74]
For example, in #66 the `light` command is used to control the brightness.
I am wondering, whether there could be a way to control the commands (and icon path) without modifying the cloned repo.

For example, by reading the values from a lua table (and providing the defaults you are already using).
This way, the table could be written before the widget is added to the wibox.

I use the icons from [mate icon theme](https://github.com/mate-desktop/mate-icon-theme/tree/master/mate/scalable/status), but had to overwrite the path inside the repo. Feels meh.

@streetturtle Would you accept PRs in this regard?

**Comment by streetturtle** [comment]
Totally agree with you, was thinking about it, cannot decided which option is better. I came up with two approaches:
 - using a table from a config file, as you suggested. I use it in weather and translate widgets - there is a `secrets.lua` file which has an API keys and some other configs. This works great but the file is still in the repo. Maybe as part of "installation" process user should copy this config file one level up, under `./.config/awesome/` folder to make it not trackable by git.
 - put all these configs inside a theme file.

First option seems to be much better, as widgets' configs are not part of a theme. 
If you already have something, feel free to create a PR. Otherwise I'll do it, as it has to be done for all widgets, and I have all of them set up on my machine.

**Comment by Ryuno-Ki** [comment]
I only have a subset of them installed today.

I was wondering whether another option would be possible:
* Passing them as part of an initialisation call.

Maybe not the most idiomatic way to use it, but it could be an option for those who are not happy with the defaults.

**Comment by streetturtle** [comment]
You mean when they are added to the wibox, something like:

```lua
s.mywibox:setup {
    ...
    battery_widget({
        cmd = 'acpi -i',
        icon =  '/path/to/icon',
        warning_text=`Battery`
    })
```
That could work, but I'm afraid it will pollute `rc.lua`, which is already quite big. But maybe it's ok. 

If you have something I would be happy to have a look.

**Comment by streetturtle** [comment]
I created a branch for this issue.  
Is this what you meant: https://github.com/streetturtle/awesome-wm-widgets/commit/75c195782d7d4ad7f4707e0ac53dd1439ae344e5?

**Comment by Ryuno-Ki** [comment]
From reading it looks way better. How would I test it?
Checking out your branch and restart awesome? Or are more things needed?

**Comment by streetturtle** [comment]
That would be very helpful if you can test it. 
You'll need just one more thing - add parentheses to the widget, because now it's a [function](https://github.com/streetturtle/awesome-wm-widgets/tree/74-externalize-config/volumearc-widget). And it's only volumearc widget for now.

**Comment by Ryuno-Ki** [comment]
Works. I highlighted the „main_color”. See the purple arc in the top bar.

![volumearc](https://user-images.githubusercontent.com/3097194/55282872-9cd06100-534d-11e9-86b0-291189e4d4f7.png)

**Comment by streetturtle** [comment]
Cool! So I'll do the same changes for the other widgets. Thank you!!!

**Comment by Ryuno-Ki** [comment]
Looking forward to it!
Be aware, that this is a breaking change (e.g. a major update). You should highlight that, so people who upgrade know that they need to adjust their config.
